/** Entorno */
export const IS_PRODUCTION = !__DEV__;
export const API_URL = 'https://api.spotify.com/v1/';
export const TOKEN =
  'BQDVzWkHUdMjyc0YnzJbr3s_y7Ce4soPe1jpkDJYXLnspcPnf2S7ZNBikDPD22DCEoEz0gzHoKEg2EZOw1q_Id6DtQXoOaga7MX0jaPf5mLc_heULQGXJUThHzQ_UXiNvSstXIveHP6G7kTKrP9PpLcP_UFRSU_UH9Thj2zCD_kv9Rm0QXd7tIDMEeR5PoKbyCGVMnPTPA1gJG3sI7Fe874jNEOsXZ67s6Cg44NInwldIm5Ddwam3STOVjsrEKKTws3HsbEXp5X_KcegbdvvAYpTUfwAz5cujqUxexsAxvQj';
